# Generated by Django 5.2.1 on 2025-05-29 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=400)),
                ("title", models.CharField(max_length=400)),
                ("heading", models.CharField(blank=True, max_length=400, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("text_area", models.TextField(max_length=200)),
                ("duration", models.DurationField()),
            ],
        ),
        migrations.DeleteModel(
            name="ContactInfo",
        ),
        migrations.DeleteModel(
            name="PortfolioItem",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.RemoveField(
            model_name="about",
            name="Age",
        ),
        migrations.RemoveField(
            model_name="about",
            name="City",
        ),
        migrations.RemoveField(
            model_name="about",
            name="Degree",
        ),
        migrations.RemoveField(
            model_name="about",
            name="Email",
        ),
        migrations.RemoveField(
            model_name="about",
            name="Freelance",
        ),
        migrations.RemoveField(
            model_name="about",
            name="Phone",
        ),
        migrations.RemoveField(
            model_name="about",
            name="Profile",
        ),
        migrations.RemoveField(
            model_name="about",
            name="Website",
        ),
        migrations.RemoveField(
            model_name="about",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="about",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="Gender",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="about",
            name="heading",
            field=models.CharField(default="Default Heading", max_length=300),
        ),
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.profile"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="age",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="about",
            name="city",
            field=models.CharField(default="Lucknow", max_length=100),
        ),
        migrations.AddField(
            model_name="about",
            name="degree",
            field=models.CharField(default="Bca", max_length=100),
        ),
        migrations.AddField(
            model_name="about",
            name="email",
            field=models.EmailField(default="sani123@gmail.com", max_length=254),
        ),
        migrations.AddField(
            model_name="about",
            name="freelance",
            field=models.CharField(default="Available", max_length=100),
        ),
        migrations.AddField(
            model_name="about",
            name="phone",
            field=models.CharField(default="0000000000", max_length=20),
        ),
        migrations.AddField(
            model_name="about",
            name="profile",
            field=models.OneToOneField(
                default=7755027538,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="website",
            field=models.CharField(default="https://example.com", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                default="MALE",
                max_length=6,
            ),
        ),
    ]
