# Generated by Django 5.2.1 on 2025-06-17 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0012_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summary",
            name="Email",
        ),
        migrations.RemoveField(
            model_name="summary",
            name="Profile",
        ),
        migrations.AddField(
            model_name="summary",
            name="college",
            field=models.CharField(default="KNIPSS College Sultanpur", max_length=100),
        ),
        migrations.AddField(
            model_name="summary",
            name="name",
            field=models.CharField(default="Sani Yadav", max_length=50),
        ),
        migrations.AddField(
            model_name="summary",
            name="phone",
            field=models.CharField(default="7755027538", max_length=20),
        ),
        migrations.AddField(
            model_name="summary",
            name="summary",
            field=models.CharField(
                default="A motivated BCA student...", max_length=500
            ),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.profile"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="summary",
            name="email",
            field=models.EmailField(default="saniyadav7755@gmail.com", max_length=254),
        ),
        migrations.AddField(
            model_name="summary",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.profile",
            ),
        ),
    ]
