# Generated by Django 5.2.1 on 2025-06-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0014_remove_resume_duration_remove_resume_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=100)),
                ("msg", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="summary",
            name="name",
            field=models.CharField(default="Sani", max_length=50),
        ),
    ]
