# Generated by Django 5.2.1 on 2025-06-20 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0016_training_company_training_heading"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="msg",
            new_name="message",
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
