# Generated by Django 5.2.1 on 2025-05-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile"),
                ),
                ("heading", models.TextField(max_length=300)),
                ("dob", models.DateTimeField(blank=True, null=True)),
                ("Website", models.CharField(max_length=50)),
                ("Phone", models.CharField(max_length=200)),
                ("City", models.CharField(max_length=200)),
                ("Age", models.CharField(blank=True, null=True)),
                ("Degree", models.CharField(max_length=200)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Freelance", models.CharField(max_length=200)),
                (
                    "Profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.profile"
                    ),
                ),
            ],
        ),
    ]
