# Generated by Django 5.2.1 on 2025-05-29 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_alter_about_city_alter_about_degree_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="heading",
        ),
    ]
