# Generated by Django 5.2.1 on 2025-05-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0007_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="tag",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="text_area",
            field=models.TextField(default="Genral", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="title",
            field=models.CharField(default="My Title", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="about",
            name="heading",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="resume",
            name="tag",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="resume",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
