# Generated by Django 5.2.1 on 2025-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0008_education_date_education_duration_education_tag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_area", models.TextField(max_length=250)),
                ("profile", models.ManyToManyField(to="webapp.profile")),
            ],
        ),
    ]
