# Generated by Django 5.2.1 on 2025-05-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0009_training"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="text_area",
            field=models.TextField(),
        ),
    ]
