# Generated by Django 5.2.1 on 2025-06-04 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0011_portfolio"),
    ]

    operations = [
        migrations.CreateModel(
            name="summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254)),
                (
                    "Profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.profile"
                    ),
                ),
            ],
        ),
    ]
