# Generated by Django 5.2.1 on 2025-06-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0013_remove_summary_email_remove_summary_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="tag",
        ),
    ]
