# Generated by Django 5.2.1 on 2025-06-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0015_contact_alter_summary_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="Company",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="training",
            name="heading",
            field=models.CharField(default="", max_length=200),
        ),
    ]
