# Generated by Django 5.2.1 on 2025-06-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0017_rename_msg_contact_message_contact_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(default="Unknown", max_length=20),
            preserve_default=False,
        ),
    ]
